version: "3.8"
services:
  es01:
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2-amd64"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - network.host=0.0.0.0
  scraper-backend:
    image: "scraper-backend"
    ports:
      - "8000:8000"
  scraper-frontend:
    image: "scraper-frontend"
    ports:
      - "8080:8080"
